name: 'Continous Integration'

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  continuos-integration:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x

      - name: Install
        run: yarn install
